services:
  - type: web
    name: fundor-eu
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: FUNDOR_COOKIE_SECURE
        value: "true"
      - key: APP_KEY
        generateValue: true

